# Generated by Django 2.2.14 on 2022-09-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animalito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_animalito', models.CharField(max_length=250)),
                ('codigo_animalito', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Loteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_jugada', models.TimeField()),
                ('monto_jugada', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('codigo_jugada', models.CharField(max_length=250)),
                ('relacion_animalito', models.ManyToManyField(to='LoteriaApp.Animalito')),
            ],
        ),
    ]
