# Generated by Django 2.2.14 on 2022-11-13 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animalito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_animalito', models.CharField(max_length=250)),
                ('codigo_animalito', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='hora_jugada_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_en_nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Loteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_jugada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado', models.DateField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('hora_relacion', models.ManyToManyField(to='LoteriaApp.hora_jugada_model')),
                ('relacion_animalito', models.ManyToManyField(to='LoteriaApp.Animalito')),
            ],
        ),
        migrations.CreateModel(
            name='monto_divisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_en_dolares', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_de_loteria_jugada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_loteria', models.CharField(max_length=150)),
                ('codigo_tipo_loteria', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='venta_procesada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_jugada', models.CharField(max_length=250)),
                ('creado', models.DateField(auto_now_add=True)),
                ('monto_final_jugadas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pago_realizado', models.BooleanField(default=True)),
                ('relacion_model_loteria', models.ManyToManyField(to='LoteriaApp.Loteria')),
            ],
        ),
        migrations.AddField(
            model_name='loteria',
            name='tipo_loteria_relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoteriaApp.tipo_de_loteria_jugada'),
        ),
    ]
