# Generated by Django 2.2.14 on 2022-09-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoteriaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteria',
            name='monto_jugada',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
    ]
