# Generated by Django 2.2.14 on 2022-11-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoteriaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loteria',
            name='tipo_loteria_relacion',
        ),
        migrations.AddField(
            model_name='loteria',
            name='tipo_loteria_relacion',
            field=models.ManyToManyField(to='LoteriaApp.tipo_de_loteria_jugada'),
        ),
    ]
