# Generated by Django 2.2.14 on 2022-09-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoteriaApp', '0002_auto_20220913_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_de_loteria_jugada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_loteria', models.CharField(max_length=150)),
                ('codigo_tipo_loteria', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='loteria',
            name='tipo_loteria_relacion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='LoteriaApp.tipo_de_loteria_jugada'),
            preserve_default=False,
        ),
    ]
