# Generated by Django 2.2.14 on 2022-11-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoteriaApp', '0002_auto_20221113_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta_procesada',
            name='hora',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
