# Generated by Django 2.2.14 on 2022-09-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoteriaApp', '0003_auto_20220916_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteria',
            name='monto_jugada',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
