# Generated by Django 2.2.14 on 2022-09-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoteriaApp', '0005_loteria_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteria',
            name='creado',
            field=models.DateField(auto_now_add=True),
        ),
    ]
