# Generated by Django 2.2.14 on 2022-09-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoteriaApp', '0007_monto_divisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monto_divisa',
            name='monto_en_dolares',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
