# Generated by Django 2.2.14 on 2022-09-27 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoteriaApp', '0008_auto_20220920_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='hora_jugada_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_en_nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='loteria',
            name='hora_jugada',
        ),
        migrations.AddField(
            model_name='loteria',
            name='hora_relacion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='LoteriaApp.hora_jugada_model'),
            preserve_default=False,
        ),
    ]
