# Generated by Django 2.2.14 on 2022-09-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoteriaApp', '0009_auto_20220927_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loteria',
            name='hora_relacion',
        ),
        migrations.AddField(
            model_name='loteria',
            name='hora_relacion',
            field=models.ManyToManyField(to='LoteriaApp.hora_jugada_model'),
        ),
    ]
