# Generated by Django 2.2.14 on 2022-09-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoteriaApp', '0010_auto_20220927_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteria',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='venta_procesada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion_model_loteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoteriaApp.Loteria')),
            ],
        ),
    ]
