# Generated by Django 2.2.14 on 2022-09-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoteriaApp', '0011_auto_20220928_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta_procesada',
            name='pago_realizado',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='venta_procesada',
            name='relacion_model_loteria',
        ),
        migrations.AddField(
            model_name='venta_procesada',
            name='relacion_model_loteria',
            field=models.ManyToManyField(to='LoteriaApp.Loteria'),
        ),
    ]
